VAGRANTFILE_API_VERSION = "2"

# Require YAML module
require 'yaml'
require 'Time'

# Get timezone
timezone = Time.now.zone()

# Read YAML file with box details
servers = YAML.load_file('servers.yaml')

# Create boxes
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

if Vagrant.has_plugin?("vagrant-timezone")
     config.timezone.value=timezone
  end

  # Iterate through entries in YAML file

  (1..3).each do |id|
    config.vm.define k8s-node-#{id} do |srv|
      srv.vm.box = qarham/ubuntu-1604-250G
      srv.vm.hostname = k8s-node-#{id}
      srv.vm.network "private_network", ip: "192.168.50.#{id}",
        virtualbox__intnet: network_#{id}"
      srv.vm.provision "shell", path: "scripts/install_3rd_pack.sh"
      srv.vm.provision "shell", path: "scripts/ntp.sh"
      srv.vm.provision "shell", path: "scripts/enable_root_login.sh"
#      srv.hostmanager.enabled = true
#      srv.hostmanager.manage_host = true
      srv.vm.provider :virtualbox do |vb|
        vb.name = servers["name"]
        vb.memory = servers["ram"]
        if servers.has_key?("cpus")
          vb.cpus = servers["cpus"]
          vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.1", "1"]
          vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.2", "1"]
          vb.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
          end
        end
      end
  end
    config.vm.define "k8s-node1" do |web|
      web.vm.provision "OSH-Install", run: "never", type:  "shell",
        path: "scripts/provision-osh-helm.sh"
    end
    config.vm.define "k8s-node1" do |web|
      web.vm.provision "TF-Install", run: "never", type:  "shell",
        path: "scripts/provision-tf-parent-chart-helm.sh"
    end
    config.vm.define "k8s-node1" do |web|
      web.vm.provision "Test-VN-VM", run: "never", type:  "shell",
        path: "scripts/mn-basic-sanity-test.sh"
    end
end
